//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDR_MENU1                       102
#define IDR_ACCELERATOR1                103
#define IDD_WINDOW                      104
#define IDC_POINTER                     104
#define IDI_ICON1                       105
#define IDD_CONTROL                     106
#define IDD_SHEET_VIEW                  108
#define IDD_SHEET_LUNG                  109
#define IDD_SHEET_REGION                109
#define IDD_COLOR_PICKER                111
#define IDD_SHEET_ATTRIBUTE             112
#define IDC_BRUSH_15                    112
#define IDC_BRUSH_0                     113
#define IDD_CALIBRATION_PARAM           113
#define IDC_BRUSH_7                     114
#define IDD_GC_PARAM                    114
#define IDD_GSD                         114
#define IDC_BRUSH_1                     115
#define IDD_PATTERN_ATTRIBUTE           115
#define IDC_BRUSH_2                     116
#define IDD_CT_ATTRIBUTE                116
#define IDC_BRUSH_3                     117
#define IDD_GC                          117
#define IDC_BRUSH_4                     118
#define IDD_DICOM_SERIES                118
#define IDC_BRUSH_5                     119
#define IDC_BRUSH_6                     120
#define IDC_BRUSH_8                     121
#define IDC_BRUSH_9                     122
#define IDC_BRUSH_10                    123
#define IDC_BRUSH_11                    124
#define IDC_BRUSH_12                    125
#define IDC_BRUSH_13                    126
#define IDC_BRUSH_14                    127
#define IDC_EDIT_SIZE                   1000
#define IDC_EDIT_OFFSET                 1001
#define IDC_EDIT_LUNG_EXTRACT_DOWNLIMIT 1001
#define IDC_EDIT_EXTRACT_DOWNLIMIT      1001
#define IDC_EDIT_LEVEL                  1001
#define IDC_EDIT_LUNG_MODIFY_DIRATION   1002
#define IDC_EDIT_MODIFY_CLOSING         1002
#define IDC_EDIT_CTATTRIBUTE            1002
#define IDC_EDIT_LUNG_MODIFY_EROSION    1003
#define IDC_EDIT_MODIFY_OPENING         1003
#define IDC_UPDATE                      1004
#define IDC_EDIT_BRUSH                  1004
#define IDC_UPDATE_LUNG_MODIFY          1005
#define IDC_UPDATE_MODIFY               1005
#define IDC_SLIDER_SIZE                 1009
#define IDC_SLIDER_OFFSET               1010
#define IDC_SLIDER_LUNG_EXTRACT_DOWNLIMIT 1010
#define IDC_SLIDER_EXTRACT_DOWNLIMIT    1010
#define IDC_SLIDER_LEVEL                1010
#define IDC_SLIDER_BRUSH                1011
#define IDC_SLIDER_SLICE                1013
#define IDC_PROGRESS                    1014
#define IDC_EDIT_SLICE                  1018
#define IDC_TREE                        1019
#define IDC_COMBO_VIEWMODE              1020
#define IDC_COMBO_SIDE                  1021
#define IDC_EDIT_INFORMATION            1022
#define IDC_TAB                         1023
#define IDC_BUTTON_LUNG_EXTRACT         1028
#define IDC_BUTTON_EXTRACT              1028
#define IDC_BUTTON_LUNG_MODIFY          1029
#define IDC_BUTTON_MODIFY               1029
#define IDC_UPDATE_LUNG_EXTRACT         1030
#define IDC_UPDATE_EXTRACT              1030
#define IDC_PREVIEW                     1030
#define IDC_SLIDER_LUNG_EXTRACT_UPLIMIT 1031
#define IDC_SLIDER_EXTRACT_UPLIMIT      1031
#define IDC_EDIT_LUNG_EXTRACT_UPLIMIT   1032
#define IDC_EDIT_EXTRACT_UPLIMIT        1032
#define IDC_BUTTON_EXTRACT_STOP         1033
#define IDC_EDIT_VOLUME                 1033
#define IDC_CHECK_3D                    1034
#define IDC_ALL_EXTRACT                 1034
#define IDC_EDIT_AVERAGE                1034
#define IDC_ALL                         1034
#define IDC_EDIT_NAME                   1035
#define IDC_BUTTON_MODIFY_STOP          1035
#define IDC_EDIT_VARIANCE               1035
#define IDC_EDIT_STANDARD_DEVIATION     1035
#define IDC_ALL_MODIFY                  1036
#define IDC_EDIT_POSTFIX                1036
#define IDC_EDIT_TOP_MIDDLE             1036
#define IDC_EDIT_COMMENT                1037
#define IDC_RADIO_RED                   1038
#define IDC_RADIO_GREEN                 1039
#define IDC_RADIO_BLUE                  1040
#define IDC_RADIO_HUE                   1041
#define IDC_RADIO_SATURATION            1042
#define IDC_RADIO_VALUE                 1043
#define IDC_RADIO_ALPHA                 1044
#define IDC_ORIGINAL_COLOR              1051
#define IDC_CURRENT_COLOR               1052
#define IDC_REGION_ALPHA                1052
#define IDC_COLOR_PICKER                1053
#define IDC_COLOR_CONTROL               1054
#define IDC_SLIDER_CONTROL              1055
#define IDC_COMBO_TARGET                1056
#define IDC_TREE_REGION                 1057
#define IDC_REGION_COLOR                1058
#define IDC_EDIT_AREA                   1059
#define IDC_BRUSH_SIZE_0                1061
#define IDC_BRUSH_SIZE_7                1062
#define IDC_BRUSH_SIZE_15               1063
#define IDC_APPEND_REGION_BY_BRUSH      1064
#define IDC_CHECK_AIR                   1065
#define IDC_EDIT_AIR                    1066
#define IDC_CHECK_WATER                 1067
#define IDC_EDIT_WATER                  1068
#define IDC_COMBO_OPERATION_MODE        1070
#define IDC_BRUSH_ENABLE                1071
#define IDC_EDIT_START                  1072
#define IDC_EDIT_MAXIMUM                1073
#define IDC_EDIT_END                    1074
#define IDC_CHECK_PATTERN_VALID         1074
#define IDC_EDIT_SPACE                  1074
#define IDC_EDIT_STEP                   1075
#define IDC_BUTTON_DELETE_PATTERN       1075
#define IDC_EDIT_COUNT                  1076
#define IDC_BUTTON_CHANGE_PATTERN       1076
#define IDC_COMBO_LUNG_TOP_BOTTOM       1076
#define IDC_COMBO_LUNG_FRONT_REAR       1077
#define IDC_BOTTOM                      1077
#define IDC_BUTTON_DELETE_ALL_PATTERN   1077
#define IDC_PRONE                       1078
#define IDC_EDIT_BOTTOM_MIDDLE          1079
#define IDC_CHANGE_CTATTRIBUTE          1080
#define IDC_EDIT_SD                     1081
#define IDC_LIST_SERIES                 1084
#define IDM_OPEN                        40002
#define IDM_QUIT                        40003
#define IDM_CLOSE                       40004
#define IDM_WINDOW                      40005
#define IDM_VIEW_CAMERA_INITIALIZE      40006
#define IDM_SAVE                        40009
#define IDM_SAVE_HISTOGRAM              40010
#define IDM_VIEW_PREV_SLICE             40011
#define IDM_VIEW_NEXT_SLICE             40012
#define IDM_VIEW_CONSOLIDATION          40013
#define IDM_VIEW_LUNG                   40014
#define IDM_VIEW_ALVEOLUS               40015
#define IDM_VIEW_AIR                    40016
#define IDM_VIEW_GROUNDGLASS            40017
#define IDM_OPERATION_DIVIDEREGION_THRESHHOLD 40018
#define IDM_OPERATION_DIVIDEREGION_CORRELATION 40019
#define IDM_OPERATION_DIVIDEREGION_SMOOTHEDDIFFERENCE 40020
#define IDM_OPERATION_DIVIDEREGION_APPROXIMATE 40021
#define IDM_SAVE_AS                     40022
#define IDM_LOAD_AS                     40023
#define IDM_ANALYSIS                    40024
#define IDM_OPERATION_DIVIDEREGION_MULTI_CORRELATION 40025
#define IDM_VIEW_ORIGINAL               40026
#define IDM_VIEW_MIX                    40027
#define IDM_VIEW_LABEL                  40028
#define IDM_ANALYSIS_VARIANCE_AVERAGE   40029
#define IDM_UNDO                        40030
#define IDM_REDO                        40031
#define IDM_VIEW_CAMERA_ROTATION        40032
#define IDM_CLEAR_UNDO                  40033
#define IDM_VIEW_HUMAN                  40034
#define IDM_OPERATION_CALIBRATION       40035
#define IDM_VIEW_BOTH                   40036
#define IDM_VIEW_LEFT                   40037
#define IDM_VIEW_RIGHT                  40038
#define IDM_OPERATION_DIVIDEREGION_CORRELATION_MULTI_PARAM 40040
#define IDM_OPERATION_DIVIDEREGION_SMOOTHEDDIFFERENCE_MULTI_PARAM 40041
#define IDM_OPERATION_REMOVE_SMALL_LUNG_REGION 40045
#define IDM_ANALYSIS_SAVE_HISTOGRAM     40046
#define IDM_VIEW_HONEYCOMBLUNG          40047
#define IDM_VIEW_GRAIN                  40048
#define IDM_VIEW_LINE                   40049
#define IDM_VIEW_NET                    40050
#define IDM_OPERATION_DIVIDEREGION_THRESHHOLD_SINGLE_SLICE 40051
#define IDM_OPERATION_DIVIDEREGION_SMOOTHEDDIFFERENCE_SINGLE_SLICE 40052
#define IDM_OPERATION_DIVIDEREGION_CORRELATION_SINGLE_SLICE 40053
#define IDM_OPERATION_DIVIDEREGION_MULTI_CORRELATION_SINGLE_SLICE 40054
#define IDM_OPERATION_DIVIDEREGION_APPROXIMATE_SINGLE_SLICE 40055
#define IDM_OPERATION_DIVIDEREGION_KOLMOGOROVSMIRNOV 40056
#define IDM_OPERATION_DIVIDEREGION_KOLMOGOROVSMIRNOV_SINGLE_SLICE 40057
#define IDM_LOAD_PATTERN                40058
#define IDM_SAVE_PATTERN                40059
#define IDM_ADD_PATTERN                 40060
#define IDM_LOAD_LABEL_AS               40061
#define IDM_ANALYSIS_RECOGNITION_NETLIKE 40063
#define IDM_COPY                        40065
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION 40066
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION_SINGLE_SLICE 40067
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION_WITH_EDGE_SINGLE_SLICE 40068
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION_WITH_EDGE 40069
#define IDM_VIEW_NORMAL                 40070
#define IDM_OPERATION_GAUSSIAN_SD       40071
#define IDM_ANALYSIS_SAVE_DISTORIBUTION 40072
#define IDM_SAVE_GRAPH                  40073
#define IDM_VIEW_TIMES1                 40074
#define IDM_VIEW_TIMES2                 40075
#define IDM_VIEW_TIMES4                 40076
#define IDM_VIEW_FIT                    40077
#define IDM_ANALYSIS_LUNG               40078
#define IDM_ANALYSIS_SAVE_INFORMATION   40079
#define IDM_OPERATION_DIVIDEREGION_MULTI_NORMALIZED_CORRELATION 40080
#define IDM_OPERATION_DIVIDEREGION_MULTI_NORMALIZED_CORRELATION_SINGLE_SLICE 40081
#define ID_Menu                         40082
#define IDM_SAVE_PATTERN_SETTING        40083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40084
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
