//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CAD4MI.rc
//
#define IDR_MENU1                       101
#define IDI_ICON1                       105
#define IDM_QUIT                        40003
#define IDM_CLOSE                       40004
#define IDM_VIEW_CAMERA_INITIALIZE      40006
#define IDM_SAVE                        40009
#define IDM_SAVE_HISTOGRAM              40010
#define IDM_VIEW_PREV_SLICE             40011
#define IDM_VIEW_NEXT_SLICE             40012
#define IDM_VIEW_LUNG                   40014
#define IDM_OPERATION_DIVIDEREGION_THRESHHOLD 40018
#define IDM_OPERATION_DIVIDEREGION_CORRELATION 40019
#define IDM_OPERATION_DIVIDEREGION_SMOOTHEDDIFFERENCE 40020
#define IDM_SAVE_AS                     40022
#define IDM_LOAD_AS                     40023
#define IDM_ANALYSIS                    40024
#define IDM_OPERATION_DIVIDEREGION_MULTI_CORRELATION 40025
#define IDM_VIEW_ORIGINAL               40026
#define IDM_VIEW_MIX                    40027
#define IDM_VIEW_LABEL                  40028
#define IDM_ANALYSIS_VARIANCE_AVERAGE   40029
#define IDM_UNDO                        40030
#define IDM_REDO                        40031
#define IDM_VIEW_CAMERA_ROTATION        40032
#define IDM_CLEAR_UNDO                  40033
#define IDM_VIEW_HUMAN                  40034
#define IDM_OPERATION_CALIBRATION       40035
#define IDM_VIEW_BOTH                   40036
#define IDM_VIEW_LEFT                   40037
#define IDM_VIEW_RIGHT                  40038
#define IDM_OPERATION_DIVIDEREGION_CORRELATION_MULTI_PARAM 40040
#define IDM_OPERATION_DIVIDEREGION_SMOOTHEDDIFFERENCE_MULTI_PARAM 40041
#define IDM_OPERATION_REMOVE_SMALL_LUNG_REGION 40045
#define IDM_ANALYSIS_SAVE_HISTOGRAM     40046
#define IDM_OPERATION_DIVIDEREGION_THRESHHOLD_SINGLE_SLICE 40051
#define IDM_OPERATION_DIVIDEREGION_SMOOTHEDDIFFERENCE_SINGLE_SLICE 40052
#define IDM_OPERATION_DIVIDEREGION_CORRELATION_SINGLE_SLICE 40053
#define IDM_OPERATION_DIVIDEREGION_MULTI_CORRELATION_SINGLE_SLICE 40054
#define IDM_OPERATION_DIVIDEREGION_KOLMOGOROVSMIRNOV 40056
#define IDM_OPERATION_DIVIDEREGION_KOLMOGOROVSMIRNOV_SINGLE_SLICE 40057
#define IDM_LOAD_PATTERN                40058
#define IDM_SAVE_PATTERN                40059
#define IDM_ADD_PATTERN                 40060
#define IDM_LOAD_LABEL_AS               40061
#define IDM_ANALYSIS_RECOGNITION_NETLIKE 40063
#define IDM_COPY                        40065
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION 40066
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION_SINGLE_SLICE 40067
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION_WITH_EDGE_SINGLE_SLICE 40068
#define IDM_OPERATION_DIVIDEREGION_NORMALIZED_CORRELATION_WITH_EDGE 40069
#define IDM_VIEW_NORMAL                 40070
#define IDM_OPERATION_GAUSSIAN_SD       40071
#define IDM_ANALYSIS_SAVE_DISTORIBUTION 40072
#define IDM_SAVE_GRAPH                  40073

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
